version: "4"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      MUSIC_BOT_NAME: $MUSIC_BOT_NAME
      OWNER_USERNAME: $OWNER_USERNAME
      SESSION_NAME: $SESSION_NAME
      DURATION_LIMIT: $DURATION_LIMIT
      BOT_USERNAME: $BOT_USERNAME
      BOT_NAME: $BOT_NAME
      ALIVE_NAME: $ALIVE_NAME
      OWNER_NAME: $OWNER_NAME
      SUDO_USERS: $SUDO_USERS
      UPDATES_CHANNEL: $UPDATES_CHANNEL
      GROUP_SUPPORT: $GROUP_SUPPORT
      OWNER_ID: $OWNER_ID
